# Generated by Django 3.2.8 on 2021-10-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='mode',
            field=models.BooleanField(default=False),
        ),
    ]
