# Generated by Django 3.2.8 on 2021-10-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_edge_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
