# Generated by Django 3.2.8 on 2021-10-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_edge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
