# Generated by Django 3.2.8 on 2021-11-09 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211109_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='timeFinish',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
