# Generated by Django 3.2.8 on 2021-11-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='bike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edge',
            name='time',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
