# Generated by Django 3.2.8 on 2021-11-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211120_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='longtitude',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='time',
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edge')),
            ],
        ),
    ]
